### ISSUE TITLE
[Google] Administrative level 1 is defined twice

### ISSUE THREAD

**Issue by guitoon** [geocoder-php/Geocoder#1173]
Hello, [this fix remove](https://github.com/geocoder-php/Geocoder/pull/943) double administrative area if they are the same. But I found an address on which Google give 2 different level 1 sublocality:

> Rue de Pont-A-Migneloux, 6210 Wayaux, Belgique

![image](https://user-images.githubusercontent.com/3265716/218494125-2699d4bd-be86-42c3-bb15-acf00861f569.png)

I this case, the geocoder give me the same error   **Administrative level 1 is defined twice**  
How can I solve this issue?

**Comment by jbelien** [comment]
A PR (#1174) is ready that should solve this issue!

```json
{
   "results" : [
      {
         "address_components" : [
            ...
            {
               "long_name" : "Les Bons Villers",
               "short_name" : "Les Bons Villers",
               "types" : [ "political", "sublocality", "sublocality_level_1" ]
            },
            {
               "long_name" : "Frasnes-lez-Gosselies",
               "short_name" : "Frasnes-lez-Gosselies",
               "types" : [ "locality", "political" ]
            },
            ...
         ],
         "formatted_address" : "Rue de Pont-à-Migneloux, 6210 Les Bons Villers, Belgique",
         ...
      }
   ],
   "status" : "OK"
}
```

In this case, it will combine the 2 `sublocality_level_1` and return `Wayaux / Les Bons Villers` as SubLocality Level 1 (see [tests](https://github.com/geocoder-php/Geocoder/pull/1174/files?diff=split&w=0#diff-f974b184bc408527b9b5012bbdd653a424030c0788cec9d061021055fbab4744R572-R591)).

**Comment by guitoon** [comment]
Nice, thank you

**Comment by jbelien** [comment]
Released: https://packagist.org/packages/geocoder-php/google-maps-provider#4.7.1

**Comment by Stalinko** [comment]
hey guys
this bug is still hapenning.

Just try to reverse these coordinates:
```
        $lat = 22.63376;
        $lng = 88.4147;
```

It will throw `Geocoder\Exception\InvalidArgument` "Administrative level 3 is defined twice".

Because the address JSON contains:

```json
            {
               "long_name" : "NDDM Ward No - 26",
               "short_name" : "NDDM Ward No - 26",
               "types" : 
               [
                  "administrative_area_level_3",
                  "political"
               ]
            },
            {
               "long_name" : "North 24 Parganas",
               "short_name" : "North 24 Parganas",
               "types" : 
               [
                  "administrative_area_level_3",
                  "political"
               ]
            },
```

And your fix doesn't help. Because the exception is thrown before `withSubLocalityLevels()` call.
Any ideas how to fix it?
